const weapons = [
    {
        'type': 'Unarmed Attacks',
        'weapons': [
            {
                'name': 'Gauntlet',
                'cost': '2 gp',
                'dmg (s)': '1d2',
                'dmg (m)': '1d3',
                'critical': 'x2',
                'range increment': '-',
                'weight': '1 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Unarmed strike',
                'cost': '',
                'dmg (s)': '1d2',
                'dmg (m)': '1d3',
                'critical': 'x2',
                'range increment': '-',
                'weight': '',
                'type': 'Bludgeoning',
            },
        ],
    },
    {
        'type': 'One-Handed Melee Weapons',
        'weapons': [
            {
                'name': 'Club',
                'cost': '',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '10 ft.',
                'weight': '3 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Mace, heavy',
                'cost': '12 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d8',
                'critical': 'x2',
                'range increment': '-',
                'weight': '8 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Morningstar',
                'cost': '8 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d8',
                'critical': 'x2',
                'range increment': '-',
                'weight': '6 lb.',
                'type': 'Bludgeoning and piercing',
            },
            {
                'name': 'Shortspear',
                'cost': '1 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '20 ft.',
                'weight': '3 lb.',
                'type': 'Piercing',
            },
        ],
    },
    {
        'type': 'Martial Weapons',
        'weapons': [
            {
                'name': 'Handaxe',
                'cost': '2 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '-',
                'weight': '2 lb.',
                'type': 'Slashing',
            },
            {
                'name': 'Kukri',
                'cost': '4 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': '18-20/x3',
                'range increment': '-',
                'weight': '2 lb.',
                'type': 'Slashing',
            },
            {
                'name': 'Pick, light',
                'cost': '8 gp',
                'dmg (s)': '1d3',
                'dmg (m)': '1d4',
                'critical': 'x2',
                'range increment': '-',
                'weight': '3 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Pick, heavy',
                'cost': '8 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '-',
                'weight': '5 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Sap',
                'cost': '1 gp',
                'dmg (s)': '1d3',
                'dmg (m)': '1d3',
                'critical': 'x2',
                'range increment': '-',
                'weight': '2 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Shield, light',
                'cost': 'special',
                'dmg (s)': '1d2',
                'dmg (m)': '1d3',
                'critical': 'x2',
                'range increment': '-',
                'weight': 'special',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Shield, heavy',
                'cost': 'special',
                'dmg (s)': '1d3',
                'dmg (m)': '1d4',
                'critical': 'x2',
                'range increment': '-',
                'weight': 'special',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Sword, short',
                'cost': '1 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '-',
                'weight': '2 lb.',
                'type': 'Piercing',
            },
        ],
    },
    {
        'type': 'Light Melee Weapons',
        'weapons': [
            {
                'name': 'Dagger',
                'cost': '2 gp',
                'dmg (s)': '1d3',
                'dmg (m)': '1d4',
                'critical': '19-20/x2',
                'range increment': '10 ft.',
                'weight': '1 lb.',
                'type': 'Piercing or slashing',
            },
            {
                'name': 'Dagger, punching',
                'cost': '2 gp',
                'dmg (s)': '1d3',
                'dmg (m)': '1d4',
                'critical': 'x3',
                'range increment': '-',
                'weight': '1 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Gauntlet, spiked',
                'cost': '5 gp',
                'dmg (s)': '1d3',
                'dmg (m)': '1d4',
                'critical': 'x2',
                'range increment': '-',
                'weight': '1 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Mace, light',
                'cost': '5 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '10 ft.',
                'weight': '4 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Sickle',
                'cost': '6 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '-',
                'weight': '2 lb.',
                'type': 'Slashing',
            },
        ],
    },
    {
        'type': 'One-Handed Melee Weapons',
        'weapons': [
            {
                'name': 'Club',
                'cost': '',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '10 ft.',
                'weight': '3 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Mace, heavy',
                'cost': '12 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d8',
                'critical': 'x2',
                'range increment': '-',
                'weight': '8 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Morningstar',
                'cost': '8 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d8',
                'critical': 'x2',
                'range increment': '-',
                'weight': '6 lb.',
                'type': 'Bludgeoning and piercing',
            },
            {
                'name': 'Shortspear',
                'cost': '1 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '20 ft.',
                'weight': '3 lb.',
                'type': 'Piercing',
            },
        ],
    },
    {
        'type': 'Two-Handed Melee Weapons',
        'weapons': [
            {
                'name': 'Longspear',
                'cost': '5 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d6/1d6',
                'dmg (m)': '1d8',
                'critical': 'x3',
                'range increment': '20 ft.',
                'weight': '9 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Quarterstaffs',
                'cost': '',
                'dmg (s)': '1d4/1d4',
                'dmg (m)': '',
                'critical': 'x2',
                'range increment': '-',
                'weight': '4 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Spear',
                'cost': '2 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d8',
                'critical': 'x3',
                'range increment': '20 ft.',
                'weight': '6 lb.',
                'type': 'Piercing',
            },
        ],
    },
    {
        'type': 'Ranged Weapons',
        'weapons': [
            {
                'name': 'Crossbow, heavy',
                'cost': '50 gp',
                'dmg (s)': '1d8',
                'dmg (m)': '1d10',
                'critical': '19-20/x2',
                'range increment': '120 ft.',
                'weight': '8 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Bolts, crossbow (10)',
                'cost': '1 gp',
                'dmg (s)': '',
                'dmg (m)': '',
                'critical': '',
                'range increment': '',
                'weight': '1 lb.',
                'type': '',
            },
            {
                'name': 'Crossbow, light',
                'cost': '35 gp',
                'dmg (s)': '1d6',
                'dmg (m)': '1d8',
                'critical': '19-20/x2',
                'range increment': '80 ft.',
                'weight': '4 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Bolts, crossbow (10)',
                'cost': '1 gp',
                'dmg (s)': '',
                'dmg (m)': '',
                'critical': '',
                'range increment': '',
                'weight': '1 lb.',
                'type': '',
            },
            {
                'name': 'Dart',
                'cost': '5 sp',
                'dmg (s)': '1d3',
                'dmg (m)': '1d4',
                'critical': 'x2',
                'range increment': '20 ft.',
                'weight': '0.5 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Javelin',
                'cost': '1 gp',
                'dmg (s)': '1d4',
                'dmg (m)': '1d6',
                'critical': 'x2',
                'range increment': '30 ft.',
                'weight': '2 lb.',
                'type': 'Piercing',
            },
            {
                'name': 'Sling',
                'cost': '',
                'dmg (s)': '1d3',
                'dmg (m)': '1d4',
                'critical': 'x2',
                'range increment': '50 ft.',
                'weight': '0 lb.',
                'type': 'Bludgeoning',
            },
            {
                'name': 'Bullets, sling (10)',
                'cost': '1 sp',
                'dmg (s)': '',
                'dmg (m)': '',
                'critical': '',
                'range increment': '',
                'weight': '5 lb.',
                'type': '',
            },
        ],
    },
];
